### PR TITLE
Update to go-vfsafero/v4

### PR DESCRIPTION
**Pull request by frelon**
This commit uses the latest version of spf13/afero and go-vfs/v4.

### CODE REVIEW

**Comment by twpayne** [comment]
Ah, this project's infrastructure was a little out of date. This is now fixed with #4.

Please could you rebase this PR on the latest `master`.

**Comment by frelon** [comment]
Awesome, thanks for the help! @twpayne

**Comment by twpayne** [comment]
Thanks! I've tagged `v4.0.0` so this should be ready for you to use.

**Comment by frelon** [comment]
Nice, seems to be working as expected!

**Pull request merged**
